name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: init
      run: sh ./ubuntu_init.sh
    - name: make_then_test
      run: sh ./clean_then_test.sh
