name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: init
      run: bash ./ubuntu_init.sh
    - name: test-all-combinations
      run: bash ./test_combination.sh
  
  windows_test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        shell: powershell
        run: |
          # choco install llvm -y
          choco install ffmpeg -y
          # refreshenv

      - name: Test environment
        shell: powershell
        run: |
          gcc --version
          Get-Command gcc | Format-List *
          #where.exe gcc

      - name: Build project
        shell: cmd
        run: |
          make CC=clang

      - name: Test project
        shell: cmd
        run: |
          make CC=clang test

