name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: init
      run: bash ./ubuntu_init.sh
    - name: Set up Emscripten
      shell: bash
      run: |
          empath=$(pwd)/emsdk_env.sh && echo "source $(empath)" >> ~/.bash_profile
    - name: make_then_test
      run: bash ./clean_then_test.sh all
  
  windows_test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        shell: powershell
        run: |
          # choco install llvm -y
          choco install ffmpeg -y
          # refreshenv

      - name: Test environment
        shell: powershell
        run: |
          gcc --version
          Get-Command gcc | Format-List *
          #where.exe gcc

      - name: Build project
        shell: cmd
        run: |
          make CC=clang

      - name: Test project
        shell: cmd
        run: |
          make CC=clang test

