name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make_then_test
      run: sh ./clean_then_test.sh all
  
  windows_test:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [mingw, clang]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MinGW environment
        if: matrix.compiler == 'mingw'
        shell: powershell
        run: |
          choco install mingw -y
          refreshenv
          gcc --version
  
      - name: Install Clang (if needed)
        if: matrix.compiler == 'clang'
        shell: powershell
        run: |
          choco install llvm -y
          refreshenv
          clang --version

      - name: Build project
        shell: cmd
        run: |
          make

      - name: Test project
        shell: cmd
        run: |
          make test

